In [5]:
import numpy as np
import pandas as pd 
import time 

ruta = r"C:\Users\javie\OneDrive\Desktop\Excel_DB\medallas.csv"
array = np.genfromtxt(ruta, delimiter=',')
print(array)


[[ nan  nan  nan  nan  nan]
 [ nan   1.   2.   3.  nan]
 [ nan   2.   2.   4.  nan]
 [ 17.   7.  22.  46.  nan]
 [  1.   1.   5.   7.  nan]
 [ nan   3.   4.   7.  nan]
 [  2.  nan  nan   2.  nan]
 [ nan   1.  nan   1.  nan]
 [  1.   3.   3.   7.  nan]
 [  3.   1.   3.   7.  nan]
 [  1.  nan  nan   1.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   6.   8.  21.  nan]
 [  3.   1.   2.   6.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   6.  11.  24.  nan]
 [  2.   4.   6.  12.  nan]
 [ nan   4.   1.   5.  nan]
 [  3.   3.   2.   8.  nan]
 [ nan  nan   1.   1.  nan]
 [  7.   3.   5.  15.  nan]
 [  4.   4.   3.  11.  nan]
 [  3.   4.   4.  11.  nan]
 [ nan   3.   2.   5.  nan]
 [  2.   1.  nan   3.  nan]
 [  1.   1.   4.   6.  nan]
 [ 39.  41.  33. 113.  nan]
 [  1.  nan   1.   2.  nan]
 [  1.   1.   2.   4.  nan]
 [  1.  nan   1.   2.  nan]
 [ nan  nan   2.   2.  nan]
 [  1.  12.  11.  33.  nan]
 [  2.   5.   1.   8.  nan]
 [  1.  11.  16.  37.  nan]
 [ nan  nan   1.   1.  nan]
 [ 22.  21.  22.  65

In [6]:

array1 = np.genfromtxt(ruta, delimiter=',', filling_values=0) # , dtype=int
print(array1)



[[  0.   0.   0.   0.   0.]
 [  0.   1.   2.   3.   0.]
 [  0.   2.   2.   4.   0.]
 [ 17.   7.  22.  46.   0.]
 [  1.   1.   5.   7.   0.]
 [  0.   3.   4.   7.   0.]
 [  2.   0.   0.   2.   0.]
 [  0.   1.   0.   1.   0.]
 [  1.   3.   3.   7.   0.]
 [  3.   1.   3.   7.   0.]
 [  1.   0.   0.   1.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.   8.  21.   0.]
 [  3.   1.   2.   6.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.  11.  24.   0.]
 [  2.   4.   6.  12.   0.]
 [  0.   4.   1.   5.   0.]
 [  3.   3.   2.   8.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   3.   5.  15.   0.]
 [  4.   4.   3.  11.   0.]
 [  3.   4.   4.  11.   0.]
 [  0.   3.   2.   5.   0.]
 [  2.   1.   0.   3.   0.]
 [  1.   1.   4.   6.   0.]
 [ 39.  41.  33. 113.   0.]
 [  1.   0.   1.   2.   0.]
 [  1.   1.   2.   4.   0.]
 [  1.   0.   1.   2.   0.]
 [  0.   0.   2.   2.   0.]
 [  1.  12.  11.  33.   0.]
 [  2.   5.   1.   8.   0.]
 [  1.  11.  16.  37.   0.]
 [  0.   0.   1.   1.   0.]
 [ 22.  21.  22.  65

In [7]:

array1 = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1) # , dtype=int 
print(array1)

[[  0.   1.   2.   3.   0.]
 [  0.   2.   2.   4.   0.]
 [ 17.   7.  22.  46.   0.]
 [  1.   1.   5.   7.   0.]
 [  0.   3.   4.   7.   0.]
 [  2.   0.   0.   2.   0.]
 [  0.   1.   0.   1.   0.]
 [  1.   3.   3.   7.   0.]
 [  3.   1.   3.   7.   0.]
 [  1.   0.   0.   1.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.   8.  21.   0.]
 [  3.   1.   2.   6.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   6.  11.  24.   0.]
 [  2.   4.   6.  12.   0.]
 [  0.   4.   1.   5.   0.]
 [  3.   3.   2.   8.   0.]
 [  0.   0.   1.   1.   0.]
 [  7.   3.   5.  15.   0.]
 [  4.   4.   3.  11.   0.]
 [  3.   4.   4.  11.   0.]
 [  0.   3.   2.   5.   0.]
 [  2.   1.   0.   3.   0.]
 [  1.   1.   4.   6.   0.]
 [ 39.  41.  33. 113.   0.]
 [  1.   0.   1.   2.   0.]
 [  1.   1.   2.   4.   0.]
 [  1.   0.   1.   2.   0.]
 [  0.   0.   2.   2.   0.]
 [  1.  12.  11.  33.   0.]
 [  2.   5.   1.   8.   0.]
 [  1.  11.  16.  37.   0.]
 [  0.   0.   1.   1.   0.]
 [ 22.  21.  22.  65.   0.]
 [  2.   1.   1.   4

In [8]:
array1 = np.genfromtxt(ruta, delimiter=',', filling_values=0, skip_header=1, dtype=int) # hace que se salte la primera fila (cabecera), los valores vacíos se llenen con 0 y los datos se conviertan a enteros
print(array1)


[[  0   1   2   3   0]
 [  0   2   2   4   0]
 [ 17   7  22  46   0]
 [  1   1   5   7   0]
 [  0   3   4   7   0]
 [  2   0   0   2   0]
 [  0   1   0   1   0]
 [  1   3   3   7   0]
 [  3   1   3   7   0]
 [  1   0   0   1   0]
 [  0   0   1   1   0]
 [  7   6   8  21   0]
 [  3   1   2   6   0]
 [  0   0   1   1   0]
 [  7   6  11  24   0]
 [  2   4   6  12   0]
 [  0   4   1   5   0]
 [  3   3   2   8   0]
 [  0   0   1   1   0]
 [  7   3   5  15   0]
 [  4   4   3  11   0]
 [  3   4   4  11   0]
 [  0   3   2   5   0]
 [  2   1   0   3   0]
 [  1   1   4   6   0]
 [ 39  41  33 113   0]
 [  1   0   1   2   0]
 [  1   1   2   4   0]
 [  1   0   1   2   0]
 [  0   0   2   2   0]
 [  1  12  11  33   0]
 [  2   5   1   8   0]
 [  1  11  16  37   0]
 [  0   0   1   1   0]
 [ 22  21  22  65   0]
 [  2   1   1   4   0]
 [  0   0   1   1   0]
 [  0   2   3   6   0]
 [  6   7   7   2   0]
 [  1   2   4   7   0]
 [  1   1   3   5   0]
 [  2   0   2   4   0]
 [  3   2   2   7   0]
 [  2   0  

In [9]:
array_ejemplo = np.array([[1, 2, 3], 
                            [4, 5, 6]])
print(array_ejemplo)

ruta2 = r"C:\Users\javie\OneDrive\Desktop\Excel_DB\mis_datoss.csv"
np.savetxt(ruta2, array_ejemplo, delimiter=',', fmt='%d') # guarda el array en un archivo CSV, utilizando la coma como delimitador y el formato de enteros)

[[1 2 3]
 [4 5 6]]
