In [1]:
import numpy as np
import pandas as pd 
import time 


array1 = np.array([1, 2, 3])
print(array1)

array2 = np.array([[0], [10], [20], [30]])
print(array2)

[1 2 3]
[[ 0]
 [10]
 [20]
 [30]]


In [2]:

broadcast_suma = array2 + array1 # broadcasting, se suman cada elemento de array1 a cada fila de array2
print(broadcast_suma)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [3]:

broadcast_mult = array2 * array1 # broadcasting, se multiplican cada elemento de array1 a cada fila de array2
print(broadcast_mult)


[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


In [4]:

# Funciones Universales
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.add(a, b) # suma elemento a elemento
print(resultado)

[5 7 9]


In [6]:

resultado2 = np.exp(a)
print(resultado2)

[ 2.71828183  7.3890561  20.08553692]


In [7]:

resultado3 = np.log(a)
print(resultado3)

[0.         0.69314718 1.09861229]


In [8]:
resultado4 = np.log10(a)
print(resultado4)

[0.         0.30103    0.47712125]


In [9]:

resultado5 = np.sqrt(a)
print(resultado5)

[1.         1.41421356 1.73205081]
