In [17]:
import numpy as np
import pandas as pd 
import time 

x = [ 1, 2, 3]
y = [ 4, 5, 6]
z = [ 7, 8, 9]

print(np.concat((x, y, z))) # concatenar arrays concat y concatenate hacen lo mismo, pero concat es mas rapido que concatenate
print(np.concatenate((x, y, z)))

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [18]:

a = [[1, 2], 
        [3, 4]]
b = [[5, 6], 
        [7, 8]]
print(np.concat([a,b], axis=1))

[[1 2 5 6]
 [3 4 7 8]]


In [19]:
print(np.concat([a,b], axis=0)) # concatenar con axis=0 es lo mismo que sin axis, pero es mas rapido que con axis=0


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
array_concat = np.concat([a,b], axis=0)
print(np.shape(array_concat))

(4, 2)


In [21]:
array_reformado = array_concat.reshape(2, 4) # reformar el array a una nueva forma, en este caso a una matriz de 2 filas y 4 columnas
print(array_reformado)

[[1 2 3 4]
 [5 6 7 8]]


In [22]:
array_sumado = array_reformado + array_reformado
print(array_sumado) 

[[ 2  4  6  8]
 [10 12 14 16]]


In [23]:
array_mult = array_reformado * array_reformado # multiplicar el array consigo mismo, lo que es lo mismo que elevar al cuadrado, pero es mas rapido que elevar al cuadrado
print(array_mult)

[[ 1  4  9 16]
 [25 36 49 64]]


In [24]:
raices = np.sqrt(array_mult) # calcular la raiz cuadrada del array, lo que es lo mismo que elevar al cuadrado y luego sacar la raiz cuadrada, pero es mas rapido que elevar al cuadrado y luego sacar la raiz cuadrada
print(raices)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
